dist: xenial

language: minimal

env:
  global:
    - DOCKSAL_VERSION=develop
    - LATEST_VERSION=mysql-5.6
  matrix:
    - VERSION=mysql-5.5
    - VERSION=mysql-5.6
    - VERSION=mysql-5.7
    - VERSION=mysql-8.0

install:
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - cd ${VERSION}
  - make
  - make test

after_success:
  - make release

after_failure:
  - make logs
