language: generic

services:
  - docker

env:
  global:
    - REPO=docksal/db
    - LATEST_VERSION=mysql-5.6
  matrix:
    - VERSION=mysql-5.5
    - VERSION=mysql-5.6
    - VERSION=mysql-5.7
    - VERSION=mysql-8.0

install:
  - curl -fsSL get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - cd ${VERSION}
  - make && make test

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
    [[ "${TRAVIS_BRANCH}" == "develop" ]] && TAG="edge-${VERSION}"
    [[ "${TRAVIS_BRANCH}" == "master" ]] && TAG="${VERSION}"
    [[ "${TRAVIS_TAG}" != "" ]] && TAG="${TRAVIS_TAG:1:3}-${VERSION}"

    if [[ "$TAG" != "" ]]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      # Push edge, stable and release tags
      docker tag ${REPO}:${VERSION} ${REPO}:${TAG}
      docker push ${REPO}:${TAG}

      # Push "latest" tag
      if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${VERSION}" == "${LATEST_VERSION}" ]]; then
        docker tag ${REPO}:${VERSION} ${REPO}:latest
        docker push ${REPO}:latest
      fi
    fi
  fi

after_failure:
  - make logs
